$RNFirebaseAsStaticFramework = true
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PanditApp' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Add RNFBDatabase pod
  # pod 'RNFBDatabase', :path => '../node_modules/@react-native-firebase/database'


  post_install do |installer|
    react_native_post_install(  
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false
  )

    # Fix for Xcode module cache and nanopb
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
      end
    end

    # Workaround for Xcode 26: newer Apple Clang breaks consteval in fmt 11.0.2.
    # Patch base.h to disable consteval since the header does not check for
    # pre-defined FMT_USE_CONSTEVAL.
    fmt_base = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      content = File.read(fmt_base)
      unless content.include?('Xcode 26 workaround')
        patched = content.gsub(
          /^(#elif defined\(__cpp_consteval\)\n#  define FMT_USE_CONSTEVAL) 1/,
          "// Xcode 26 workaround: disable consteval\n\\1 0"
        )
        if patched != content
          File.chmod(0644, fmt_base)
          File.write(fmt_base, patched)
        end
      end
    end
  end
end
